version: "3.9"

services:
  mlflow:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - D:/Mestrado/federated_learning_traffic:/mnt/mlflow
      - D:/Mestrado/federated_learning_traffic:/app

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - D:/Mestrado/federated_learning_traffic:/var/lib/postgresql/data
