version: "3.9"
services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=postgresql://mlflow:mlflow@db/mlflow
    depends_on:
      - db
    volumes:
      - ./artifacts:/app/artifacts
      - D:\Mestrado\federated_learning_traffic:/app

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=mlflow
      - POSTGRES_DB=mlflow
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: